#!/bin/bash
sudo apt update
sudo apt install wget -y
cd $HOME
sudo systemctl stop subspace-farmer.service
 sudo systemctl stop subspace-node.service
 subspace-farmer wipe
 subspace-node purge-chain --chain gemini-1
 wget https://github.com/subspace/subspace/releases/download/gemini-1b-2022-june-03/subspace-node-ubuntu-x86_64-gemini-1b-2022-june-03
 wget https://github.com/subspace/subspace/releases/download/gemini-1b-2022-june-03/subspace-farmer-ubuntu-x86_64-gemini-1b-2022-june-03
 sudo mv subspace-node-ubuntu-x86_64-gemini-1b-2022-june-03 /usr/local/bin/subspace-node
 sudo mv subspace-farmer-ubuntu-x86_64-gemini-1b-2022-june-03 /usr/local/bin/subspace-farmer
 sudo chmod +x /usr/local/bin/subspace*
 echo -e "\e[1m\e[32m8. Enter Polkadot JS address to receive rewards \e[0m"
read -p "Address: " 16cwVQ3xT2n5R3UWSEqd5Db11UdWiPfxhEXQKbDEg4zBfjcz
echo -e "\e[1m\e[32m9. Enter Subspace Node name \e[0m"
read -p "Node Name : " KDTD11
echo -e "\e[1m\e[32m9. Enter Subspace Farmer Plot Size. For example 30G (means 30 Gigabyte) \e[0m"
read -p "Plot Size : " 1024G
echo -e "\e[1m\e[91m    11.1 Continue the process (y/n) \e[0m"
read -p "(y/n)?" response
if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
[Service]
User=$USER
ExecStart=subspace-node --chain gemini-1 --execution wasm --pruning archive --validator --in-peers 100 --in-peers-light 100 --out-peers 100 --name '$NODE_NAME'
Restart=always
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
    " > $HOME/subspace-node.service

    sudo mv $HOME/subspace-node.service /etc/systemd/system
  [Service]
User=$USER
ExecStart=subspace-farmer farm --reward-address 16cwVQ3xT2n5R3UWSEqd5Db11UdWiPfxhEXQKbDEg4zBfjcz --plot-size 1024G
Restart=always
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
    " > $HOME/subspace-farmer.service

    sudo mv $HOME/subspace-farmer.service /etc/systemd/system
    sudo systemctl daemon-reload
    sudo systemctl enable subspace-farmer.service
    sudo systemctl enable subspace-node.service
    sudo systemctl restart subspace-node.service
    sudo systemctl restart subspace-farmer.service
    
